apply plugin: 'java-library'
apply plugin: 'net.serenity-bdd.aggregator'


repositories {
    mavenLocal()
    mavenCentral()
    //  jcenter()
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        //jcenter()
    }
    dependencies {

        classpath("net.serenity-bdd:serenity-gradle-plugin:2.0.80")
    }
}


dependencies {
    testImplementation 'junit:junit:4.13.2'

    // Serenity principales (traen PageObject)
    implementation 'net.serenity-bdd:serenity-core:2.6.0'
    implementation 'net.serenity-bdd:serenity-junit:2.6.0'
    implementation 'net.serenity-bdd:serenity-cucumber6:2.6.0'

    // Cucumber API para Steps
    testImplementation 'io.cucumber:cucumber-java:6.10.4'
    testImplementation 'io.cucumber:cucumber-junit:6.10.4'

    implementation 'org.slf4j:slf4j-simple:1.7.7'
    implementation 'com.google.guava:guava:23.0'
    implementation group: 'org.apache.poi', name: 'poi', version: '3.17'
    implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '3.17'
}


test {

    ignoreFailures = true
}


tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}


gradle.startParameter.continueOnFailure = true